
###
//create user
POST http://localhost:9000/api/apiusers HTTP/1.1
Content-Type: application/json

{
    "username": "Don mario",
    "email": "donmariomario@email.com",
    "password": "encriptedpasswordjeje"
}

###
//read all users
GET http://localhost:9000/api/apiusers HTTP/1.1

###
//read one user
GET http://localhost:9000/api/apiusers/67087832d842e070c890bc4c HTTP/1.1

###
//update one user
PUT http://localhost:9000/api/apiusers/670879808cfbfc58f7337700 HTTP/1.1
Content-Type: application/json

{
    "username": "Don Mario",
    "email": "donmariomario@email.com",
    "password": "encriptedpassword" 
}

###
//delete one user
DELETE http://localhost:9000/api/apiusers/670879808cfbfc58f7337700 HTTP/1.1